CREATE TABLE IF NOT EXISTS `USERS` (
	`ID` IDENTITY NOT NULL PRIMARY KEY,
	`USERNAME` VARCHAR(64) NOT NULL UNIQUE,
	`PASSWORD` CLOB NOT NULL,
	`FULLNAME` VARCHAR(128),
	`ACCESSLEVEL` TINYINT NOT NULL DEFAULT 0,
	`PREFS` CLOB NOT NULL DEFAULT '{}');

CREATE TABLE IF NOT EXISTS `PLAYLISTS` (
	`ID` IDENTITY NOT NULL PRIMARY KEY,
	`UUID` VARCHAR(33) NOT NULL UNIQUE,
	`NAME` VARCHAR(256) NOT NULL,
	`OWNER` BIGINT NOT NULL,
	`SHARED` BOOLEAN NOT NULL DEFAULT FALSE,
	`TRACKS` CLOB NOT NULL DEFAULT '',
	FOREIGN KEY(`OWNER`) REFERENCES `USERS`(`ID`));
